# Generated by Django 5.2.3 on 2025-06-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassets', '0003_user_email_user_fullname_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itassets.inventoryuser'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itassets.inventoryuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
